(load "~/Documents/SBCL/Assignment 0/ZZHANG_Q6_src.lisp")
(defvar ht (make-hash-table :test #'equal))
(defvar facts '((on A1 A2) (on A2 A5) (on-table B2 B6)))
(store-facts facts ht)
(format t "The facts: ((on A1 A2) (on A2 A5) (on-table B2 B6)) ~%")
(format t "Get the key on, expected output: ((on A1 A2) (on A2 A5)) ~%")
(format t "The real output: ~A ~%" (gethash 'on ht)) ;expect output: ((on A1 A2) (on A2 A5))
(format t "The facts: (on A2 A5) ~%, expected output: (on A2 A5) ~%")
(format t "The real output: ~A ~%"(gethash '(on A2 A5) ht)) ;expect output: (on A2 A5)
